name: firebase_ui_oauth
description: Firebase UI widgets for authentication & OAuth
version: 1.5.0
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_oauth

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  desktop_webview_auth: ^0.0.11
  firebase_auth: ^4.7.2
  firebase_ui_auth: ^1.7.0
  firebase_ui_shared: ^1.4.0
  flutter_svg: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"
  - "/example/lib/config.dart"

flutter:
