name: firebase_ui_oauth
description: Firebase UI widgets for authentication & OAuth
version: 1.5.3
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_oauth

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  desktop_webview_auth: ^0.0.14
  firebase_auth: ^5.0.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_shared: ^1.4.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"
  - "/example/lib/config.dart"

flutter:
