name: firebase_ui_auth
description: Pre-built widgets library that are integrated with the variety of the Firebase Auth providers.
version: 1.7.0
repository: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  email_validator: ^2.1.17
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_dynamic_links: ^5.3.4
  firebase_ui_localizations: ^1.6.0
  firebase_ui_oauth: ^1.4.10
  firebase_ui_shared: ^1.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0

false_secrets:
  - "/example/**/google-services.json"
  - "/example/**/firebase_options.dart"
  - "/example/**/GoogleService-Info.plist"
  - "example/lib/config.dart"

flutter:
