name: firebase_ui_auth
description: Pre-built widgets library that are integrated with the variety of the Firebase Auth providers.
version: 3.0.0
repository: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth
homepage: https://github.com/firebase/FirebaseUI-Flutter/tree/master/packages/firebase_ui_auth

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  app_links: ^6.4.0
  email_validator: ^2.1.17
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_ui_localizations: ^2.0.0
  firebase_ui_oauth: ^2.0.0
  firebase_ui_shared: ^1.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4

false_secrets:
  - example/**

flutter:
